# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Admin.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')Merchant.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

DeviceInfo.create(
    board: 'MSM8226', 
    brand: 'Htc', 
    cpu: 'armeabi-v7a', 
    cpu2: '', 
    device: 'htc', 
    display: '4.3.042.P3.140118.8730L', 
    fingerprint: 'htc/htc/htc:4.3/JSL36C/4.3.042.P3.140118.8730L:user/release-keys', 
    hardware: 'qcom',
    product_model: 'JLS36C',
    manufacturer: 'htc',
    model: 'htc',
    product: 'htc',
    bootloader: 'unknown',
    host: 'ubuntu',
    build_tags: '',
    incremental: 'user,USER:system5',
    )
    
DeviceInfo.create(
  board: 'MSM8226', 
  brand: 'Coolpad', 
  cpu: 'armeabi-v7a', 
  cpu2: '', 
  device: 'Coolpad8730L', 
  display: '4.3.042.P3.140118.8730L', 
  fingerprint: 'Coolpad/Coolpad8730L/Coolpad8730L:4.3/JSL36C/4.3.042.P3.140118.8730L:user/release-keys', 
  hardware: 'qcom',
  product_model: 'JLS36C',
  manufacturer: 'YuLong',
  model: 'Coolpad 8730L',
  product: 'Coolpad8730L',
  bootloader: 'unknown',
  host: 'ubuntu',
  build_tags: '',
  incremental: 'user,USER:system5',
  )

  DeviceInfo.create(
    board: 'nox', 
    brand: 'PXA988', 
    cpu: 'armeabi-v7a', 
    cpu2: '', 
    device: 'aruba3gcmcc', 
    display: 'JZO54K.I8268ZMAME1', 
    fingerprint: 'Android/samsung/samsung:4.4.4/KOT49H/3.6.1.0506:user/release-keys', 
    hardware: 'qcom',
    product_model: 'KOT49H',
    manufacturer: 'samsung',
    model: 'samsung c8813',
    product: 'c8813',
    bootloader: 'unknown',
    host: 'topaz0',
    build_tags: '',
    incremental: 'user,USER:dpi',
    )

    DeviceInfo.create(
      board: 'msm8996', 
      brand: 'samsung', 
      cpu: 'arm64-v8a', 
      cpu2: '', 
      device: 'hero2qltechn', 
      display: 'NRD90M.G9350ZHU2BQL3', 
      fingerprint: 'samsung/hero2qltezh/hero2qltechn:7.0/NRD90M/G9350ZHU2BQL3:user/release-keys', 
      hardware: 'qcom',
      product_model: 'NRD90M',
      manufacturer: 'samsung',
      model: 'SM-G9503',
      product: 'hero2qltezh',
      bootloader: 'unknown',
      host: 'SWDG4703',
      build_tags: '',
      incremental: 'user,USER:dpi',
      )
      
      DeviceInfo.create(
        board: 'unknown', 
        brand: 'Xiaomi', 
        cpu: 'arm64-v8a', 
        cpu2: '', 
        device: 'hermes', 
        display: 'LRX22G', 
        fingerprint: 'xiaomi/hermes/hermes:5.0.2/LRX22G/V8.5.2.0.LHMCNED:user/release-keys', 
        hardware: 'mt6795',
        product_model: 'LRX22G',
        manufacturer: 'Xiaomi',
        model: 'Redmi Note2',
        product: 'hermes',
        bootloader: 'unknown',
        host: 'c3-miui-ota-bd08.bj',
        build_tags: '',
        incremental: 'user,USER:root',
        )
        
        DeviceInfo.create(
          board: 'unknown', 
          brand: 'xiaomi', 
          cpu: 'armeabi-v7', 
          cpu2: '', 
          device: 'HM2014501', 
          display: 'KOT49H', 
          fingerprint: 'xiaomi/2014501/HM2014501:4.4.2/KOT49H/V9.2.2.0.KHHCNEK:user/release-keys', 
          hardware: 'mt6582',
          product_model: 'KOT49H',
          manufacturer: 'Xiaomi',
          model: 'Redmi 2',
          product: 'Redmi 2',
          bootloader: 'unknown',
          host: 'c3-miui-ota-bd14.bj',
          build_tags: '',
          incremental: 'user,USER:root',
          )
          
          
          DeviceInfo.create(
            board: 'QC_Reference_Phone', 
            brand: 'xiaomi', 
            cpu: 'arm64-v8a', 
            cpu2: '', 
            device: 'ugg', 
            display: 'N2G47H', 
            fingerprint: 'xiaomi/ugg/ugg:7.1.2/N2G47H/V9.1.7.0.NDKCNEI:user/release-keys', 
            hardware: 'qcom',
            product_model: 'N2G47H',
            manufacturer: 'Xiaomi',
            model: 'Redmi Note 5A',
            product: 'ugg',
            bootloader: 'unknown',
            host: 'c3-miui-ota-bd99.bj',
            build_tags: '',
            incremental: 'user,USER:root',
            )
            
            DeviceInfo.create(
              board: 'QC_Reference_Phone', 
              brand: 'xiaomi', 
              cpu: 'arm64-v8a', 
              cpu2: '', 
              device: 'ugg', 
              display: 'N2G47H', 
              fingerprint: 'xiaomi/ugg/ugg:7.1.2/N2G47H/V9.1.6.0.NDKCNEI:user/release-keys', 
              hardware: 'qcom',
              product_model: 'N2G47H',
              manufacturer: 'Xiaomi',
              model: 'Redmi Note 5',
              product: 'ugg',
              bootloader: 'unknown',
              host: 'c3-miui-ota-bd99.bj',
              build_tags: '',
              incremental: 'user,USER:root',
              )

              DeviceInfo.create(
                board: 'msm8953', 
                brand: 'OPPO', 
                cpu: 'arm64-v8a', 
                cpu2: '', 
                device: 'R9s', 
                display: 'R9s_11_A.24_180207', 
                fingerprint: 'OPPO/R9s/R9s:6.0.1/MMB29M/1511911518:user/release-keys', 
                hardware: 'qcom',
                product_model: 'MMb29M',
                manufacturer: 'OPPO',
                model: 'OPPO R9s',
                product: 'r9s',
                bootloader: '',
                host: 'ubuntu-121-238',
                build_tags: '',
                incremental: 'user,USER:root',
                )
                
                DeviceInfo.create(
                  board: 'msm8953', 
                  brand: 'vivo', 
                  cpu: 'arm64-v8a', 
                  cpu2: '', 
                  device: 'x9', 
                  display: 'x9_11_A.24_180207', 
                  fingerprint: 'VIVO/X9/X9:6.0.1/MMB29M/1511911515:user/release-keys', 
                  hardware: 'qcom',
                  product_model: 'MMb29M',
                  manufacturer: 'VIVO',
                  model: 'VIVO X9',
                  product: 'X9',
                  bootloader: '',
                  host: 'ubuntu-121-238',
                  build_tags: '',
                  incremental: 'user,USER:root',
                  )
                  
                  DeviceInfo.create(
                    board: 'msm8953', 
                    brand: 'vivo', 
                    cpu: 'arm64-v8a', 
                    cpu2: '', 
                    device: 'x20', 
                    display: 'x20_11_A.24_180207', 
                    fingerprint: 'VIVO/X20/X20:6.0.1/MMB29M/1111911515:user/release-keys', 
                    hardware: 'qcom',
                    product_model: 'MMb29M',
                    manufacturer: 'VIVO',
                    model: 'VIVO X20',
                    product: 'X20',
                    bootloader: '',
                    host: 'ubuntu-121-238',
                    build_tags: '',
                    incremental: 'user,USER:root',
                    )
                    
  DeviceInfo.create(
    board: 'NXT-AL10', 
    brand: 'HUAWEI', 
    cpu: 'arm64-v8a', 
    cpu2: '', 
    device: 'HWNXT', 
    display: 'NXT-AL10C00B596', 
    fingerprint: 'HUAWEI/NXT-AL10/HUAWEINXT-H:7.0/HONORPRA-AL00X/C00B221:user/release-keys', 
    hardware: 'hi3650',
    product_model: 'HUAWEINXT-AL10',
    manufacturer: 'HUAWEI',
    model: 'HUAWEI NXT-AL10',
    product: 'NXT-AL10',
    bootloader: '',
    host: 'wuhjk0381cna',
    build_tags: '',
    incremental: 'user,USER:test',
    )
    
    DeviceInfo.create(
      board: 'NXT-AL8', 
      brand: 'HUAWEI', 
      cpu: 'arm64-v8a', 
      cpu2: '', 
      device: 'HWNXT', 
      display: 'NXT-AL8C00B596', 
      fingerprint: 'HUAWEI/NXT-AL8/HUAWEINXT-H:7.0/HONORPRA-AL08X/C00B222:user/release-keys', 
      hardware: 'hi3650',
      product_model: 'HUAWEINXT-AL8',
      manufacturer: 'HUAWEI',
      model: 'HUAWEI NXT-AL8',
      product: 'NXT-AL18',
      bootloader: '',
      host: 'wuhjk0382cna',
      build_tags: '',
      incremental: 'user,USER:test',
      )
  
      DeviceInfo.create(
        board: 'M5 Note', 
        brand: 'Meizu', 
        cpu: 'arm64-v8a', 
        cpu2: '', 
        device: 'M5Note', 
        display: 'flyme 6.1.0.0A', 
        fingerprint: 'Meizu/M1621/M1621:6.0/MRA58K/1495809194:user/release-keys', 
        hardware: 'mt6755',
        product_model: 'MRA58K',
        manufacturer: 'Meizu',
        model: 'M5 Note',
        product: 'meizu_M5 Note',
        bootloader: 'booltloader',
        host: 'Mz-Builder-l3',
        build_tags: 'build',
        incremental: 'user',
        )
        
  
        DeviceInfo.create(
          board: 'M4 Note', 
          brand: 'Meizu', 
          cpu: 'arm7-v8a', 
          cpu2: '', 
          device: 'M4Note', 
          display: 'flyme 5.1.0.0A', 
          fingerprint: 'Meizu/M1621/M1621:4.0/MRA58K/1495809195:user/release-keys', 
          hardware: 'mt6755',
          product_model: 'MRA58K',
          manufacturer: 'Meizu',
          model: 'M4 Note',
          product: 'meizu_M4 Note',
          bootloader: 'booltloader',
          host: 'Mz-Builder-l3',
          build_tags: 'build',
          incremental: 'user',
          )
          
          DeviceInfo.create(
            board: 'M3 Note', 
            brand: 'Meizu', 
            cpu: 'arm7-v8a', 
            cpu2: '', 
            device: 'M3Note', 
            display: 'flyme 4.1.0.0A', 
            fingerprint: 'Meizu/M1621/M1621:3.0/MRA58K/1495809196:user/release-keys', 
            hardware: 'mt6755',
            product_model: 'MRA58K',
            manufacturer: 'Meizu',
            model: 'M3 Note',
            product: 'meizu_M3 Note',
            bootloader: 'booltloader',
            host: 'Mz-Builder-l3',
            build_tags: 'build',
            incremental: 'user',
            )
            

            DeviceInfo.create(
              board: 'hi6250', 
              brand: 'HONOR', 
              cpu: 'arm64-v8a', 
              cpu2: '', 
              device: 'HWPRA-H', 
              display: 'PRA-AL00XC00B220', 
              fingerprint: 'HONOR/RPA-AL00X/HWPRA-H:7.0/HONORPRA-AL00X/C00B220:user/release-keys', 
              hardware: 'hi6250',
              product_model: 'HONORPRA-AL00X',
              manufacturer: 'HUAWEI',
              model: 'PRA-AL00X',
              product: 'PRA-AL00X',
              bootloader: 'unknown',
              host: 'SIA1000105584',
              build_tags: 'build',
              incremental: 'user,USER:test',
              )
              
  
              DeviceInfo.create(
                board: 'hi6250', 
                brand: 'HONOR', 
                cpu: 'arm64-v8a', 
                cpu2: '', 
                device: 'HWPRA-H', 
                display: 'PRA-AL00XC00B221', 
                fingerprint: 'HONOR/RPA-AL00X/HWPRA-H:7.0/HONORPRA-AL00X/C00B220:user/release-keys', 
                hardware: 'hi6250',
                product_model: 'HONORPRA-AL00X',
                manufacturer: 'HUAWEI',
                model: 'PRA-AL00X',
                product: 'PRA-AL00X',
                bootloader: 'unknown',
                host: 'SIA1000105585',
                build_tags: 'build',
                incremental: 'user,USER:test',
                )
                

